export const UPDATE_VIEW_COLLECTION = 'UPDATE_VIEW_COLLECTION';
export const UPDATE_CATEGORY_PRODUCTS = 'UPDATE_CATEGORY_PRODUCTS';
export const INITIATE_CATEGORY_PRODUCTS='INITIATE_CATEGORY_PRODUCTS';